name: 'Drupal Starter Base'
description: 'A recipe for starting a Drupal 10 project.'
type: 'Site'

install:
  - admin_toolbar
  - admin_toolbar_tools
  - big_pipe
  - block_content
  - breakpoint
  - ckeditor5
  - config
  - contextual
  - datetime
  - editor
  - field_ui
  - file
  - gin
  - gin_toolbar
  - image
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - options
  - path
  - taxonomy
  - toolbar
  - views_ui
  - views

config:
  import:
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    block_content:
      - views.view.block_content.yml
    field_ui: '*'
    file: '*'
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
      - block.block.gin_secondary_local_tasks
    image: '*'
    media: '*'
    media_library: '*'
    menu_ui: '*'
    taxonomy: '*'
    views: '*'

  actions:
    block.block.gin_admin:
      simple_config_update:
        status: false
    block.block.gin_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simple_config_update:
        status: false
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
    block.block.gin_tools:
      simple_config_update:
        status: false
    node.settings:
      simple_config_update:
        use_admin_theme: true
    user.settings:
      simple_config_update:
        register: admin_only
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'stark'
